Add progress indicator to loading screen
git-truck/git-truck pull request #693
Opened 2023-11-18 17:04 UTC by tjomson

2023-11-18 18:54 UTC, joglr reviewed
![Screenshot_20231118-195219.png](https://github.com/git-truck/git-truck/assets/1959615/624c2429-bffe-4627-8368-7b1891b6cc8c)

Very cool feature!

Could we adjust the text tracking a bit so it is not as wide?

2023-11-20 12:54 UTC, joglr approved these changes
Awesome!

2023-11-20 12:58 UTC, tjomson commented on src/components/LoadingIndicator.tsx
> +    const { progress, totalCommitCount, analyzationStatus } = fetcher.data as {
Good point :O

2023-11-20 13:54 UTC, joglr requested changes

2023-11-20 13:54 UTC, joglr commented on src/components/LoadingIndicator.tsx
> +interface ProgressData {
Prefer type over interfaces

https://www.totaltypescript.com/type-vs-interface-which-should-you-use

2023-11-20 15:52 UTC, joglr approved these changes

2023-11-20 15:52 UTC, merged