Add filtering and sorting for Commits tab
git-truck/git-truck pull request #720
Opened 2024-01-20 23:16 UTC by dawidwoz

# Problem

Currently, there is no interaction with commits in the `Commits` but we can easily add it. 

Current state:
![image](https://github.com/git-truck/git-truck/assets/52498300/6988b548-286c-4806-a56d-b8653d14ae2a)

# Solution

I added another card where I put the sort by option, sorting order and filtering by a part of a commit message. After my changes, it looks like this:
![image](https://github.com/git-truck/git-truck/assets/52498300/ed0690eb-dd5b-42d1-8b3c-c6aaeba04e37)

Related issue: #677

2024-01-22 16:32 UTC, tjomson requested changes
Very cool, and nicely integrated with the on-demand loading of commits!
One minor thing, is that the search field is case sensitive. I think it would be best for it to not be case sensitive, as the file search field isn't.
Of course, preferably we should have a search option for both search fields to toggle case sensitivity on/off, but we will do that some other time :D

2024-01-23 16:34 UTC, dawidwoz commented
> Very cool, and nicely integrated with the on-demand loading of commits! One minor thing, is that the search field is case sensitive. I think it would be best for it to not be case sensitive, as the file search field isn't. Of course, preferably we should have an option for both search fields to toggle case sensitivity on/off, but we will do that some other time :D

Thank you for your review. It should not be case sensitive anymore. In the future, I think we should use the filters as parameters in the commits call.  So if you search "fix", you will get results from all commits, not only from those that you've loaded before. So I am going to open an issue to fix it when it is merged. We can call it - step two for the commit interaction 😉

2024-01-24 09:52 UTC, tjomson approved these changes
Epic 🚀

2024-01-24 09:52 UTC, merged

2024-01-31 10:52 UTC, dawidwoz commented
@tjomson I added the issue #722 related to my comment above that I am going to have a look into shortly.